/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface MiningConfig {
  'bitcoinPayoutAddress' : string,
  'targetHashrate' : bigint,
  'powerUsage' : bigint,
  'electricityCost' : bigint,
  'profileName' : string,
}
export interface MiningEvent {
  'timestamp' : Time,
  'details' : [] | [string],
  'eventType' : string,
}
export interface MiningState {
  'cumulativeRuntime' : bigint,
  'cumulativeEarnings' : bigint,
  'isActive' : boolean,
  'config' : MiningConfig,
  'lastStartTimestamp' : [] | [Time],
}
export interface Payout {
  'status' : string,
  'address' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface ProposalResponse {
  'note' : [] | [string],
  'accepted' : boolean,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerResponse' : ActorMethod<[], [] | [ProposalResponse]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMiningConfig' : ActorMethod<[], [] | [MiningConfig]>,
  'getMiningEvents' : ActorMethod<[], Array<MiningEvent>>,
  'getMiningState' : ActorMethod<[], [] | [MiningState]>,
  'getPayoutHistory' : ActorMethod<[], Array<Payout>>,
  'getResponse' : ActorMethod<[Principal], [] | [ProposalResponse]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestPayout' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startMining' : ActorMethod<[], undefined>,
  'stopMining' : ActorMethod<[], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'submitResponse' : ActorMethod<[boolean, [] | [string]], undefined>,
  'updateMiningConfig' : ActorMethod<[MiningConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];