/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const ProposalResponse = IDL.Record({
  'note' : IDL.Opt(IDL.Text),
  'accepted' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const MiningConfig = IDL.Record({
  'bitcoinPayoutAddress' : IDL.Text,
  'targetHashrate' : IDL.Nat,
  'powerUsage' : IDL.Nat,
  'electricityCost' : IDL.Nat,
  'profileName' : IDL.Text,
});
export const MiningEvent = IDL.Record({
  'timestamp' : Time,
  'details' : IDL.Opt(IDL.Text),
  'eventType' : IDL.Text,
});
export const MiningState = IDL.Record({
  'cumulativeRuntime' : IDL.Nat,
  'cumulativeEarnings' : IDL.Nat,
  'isActive' : IDL.Bool,
  'config' : MiningConfig,
  'lastStartTimestamp' : IDL.Opt(Time),
});
export const Payout = IDL.Record({
  'status' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerResponse' : IDL.Func([], [IDL.Opt(ProposalResponse)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMiningConfig' : IDL.Func([], [IDL.Opt(MiningConfig)], ['query']),
  'getMiningEvents' : IDL.Func([], [IDL.Vec(MiningEvent)], ['query']),
  'getMiningState' : IDL.Func([], [IDL.Opt(MiningState)], ['query']),
  'getPayoutHistory' : IDL.Func([], [IDL.Vec(Payout)], ['query']),
  'getResponse' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ProposalResponse)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestPayout' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startMining' : IDL.Func([], [], []),
  'stopMining' : IDL.Func([], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'submitResponse' : IDL.Func([IDL.Bool, IDL.Opt(IDL.Text)], [], []),
  'updateMiningConfig' : IDL.Func([MiningConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const ProposalResponse = IDL.Record({
    'note' : IDL.Opt(IDL.Text),
    'accepted' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const MiningConfig = IDL.Record({
    'bitcoinPayoutAddress' : IDL.Text,
    'targetHashrate' : IDL.Nat,
    'powerUsage' : IDL.Nat,
    'electricityCost' : IDL.Nat,
    'profileName' : IDL.Text,
  });
  const MiningEvent = IDL.Record({
    'timestamp' : Time,
    'details' : IDL.Opt(IDL.Text),
    'eventType' : IDL.Text,
  });
  const MiningState = IDL.Record({
    'cumulativeRuntime' : IDL.Nat,
    'cumulativeEarnings' : IDL.Nat,
    'isActive' : IDL.Bool,
    'config' : MiningConfig,
    'lastStartTimestamp' : IDL.Opt(Time),
  });
  const Payout = IDL.Record({
    'status' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerResponse' : IDL.Func([], [IDL.Opt(ProposalResponse)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMiningConfig' : IDL.Func([], [IDL.Opt(MiningConfig)], ['query']),
    'getMiningEvents' : IDL.Func([], [IDL.Vec(MiningEvent)], ['query']),
    'getMiningState' : IDL.Func([], [IDL.Opt(MiningState)], ['query']),
    'getPayoutHistory' : IDL.Func([], [IDL.Vec(Payout)], ['query']),
    'getResponse' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ProposalResponse)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestPayout' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startMining' : IDL.Func([], [], []),
    'stopMining' : IDL.Func([], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'submitResponse' : IDL.Func([IDL.Bool, IDL.Opt(IDL.Text)], [], []),
    'updateMiningConfig' : IDL.Func([MiningConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };